### ISSUE TITLE
AMQP Filters

### ISSUE THREAD

**Issue by timbuchwaldt** [rabbitmq/rabbitmq-amqp1.0-client#3] opened 2017-08-11 13:09 UTC
Hi!
We would like to use the AMQP 1.0 client for subscribing to Azure EventHub and need filtering support ( http://www.amqp.org/specification/1.0/filters) 

Are there any plans on supporting filtering?

**Comment by michaelklishin** [comment] 2017-08-11 13:15
There are but there is no ETA.

**Comment by hommeabeil** [comment] 2019-03-20 12:44
Hi
I am also using this lib to connect with an Azure event hub and I always got errors when using the filter. I look around and it seem the problem is the filter implementation. Taken from the [AMQP 1.0 doc](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-filter-set]) the filter should be a described type and not a string. You can look at the change [here](https://github.com/hommeabeil/rabbitmq-amqp1.0-client/pull/1). I am willing to do the full fix, later this week if the solution accepted.

**Comment by kjnilsson** [comment] 2019-03-20 12:58
@hommeabeil that change looks good to me. Please raise a PR and we can take it from there. The filter implementation was a contribution, we have little means of testing it well as we don't automate the tests suite against Azure.

**Comment by hommeabeil** [comment] 2019-03-20 13:19
@kjnilsson  Do you want the PR that I link in the issue and you will do the full fix. I am not currently set to run elixir so I can run your tests suite.

**Comment by kjnilsson** [comment] 2019-03-20 14:22
As I mentioned we haven't got a ready test system for filters and we're a small team so a full fix PR would be much more likely to me merged sooner than one that needs work.

**Comment by hommeabeil** [comment] 2019-03-20 15:12
No problem, I manage to make a working environment, I am currently working on the fix.

**Comment by lukebakken** [comment] 2020-11-16 23:15
I assume this is fixed by #17 and #28

**Closed as completed by lukebakken** 2020-11-16 23:15 UTC
